server-webhook-url: http://localhost:8040/webhooks
agent-api-url: http://localhost:8021
log-level: debug    # example: info, debug
wallet-type: askar  # example: askar, indy
public-invitation: true
revoke-after-issue: false
use-multitenancy: true
delete-data-at-exit: true

sse-server-url: http://localhost:8080 # server-sent-event server, in our case usually the datastore URL
