issuer-invitation-url: http://localhost:8040/invitation-url
agent-api-url: http://localhost:8021
log-level: debug  # info debug
wallet-type: indy  # askar indy
use-multitenancy: true
enable-webhook: false

enable-invitation-with-proof: false
issuer-invitation-url-with-proof: http://localhost:8040/invitation-url-with-proof