issuer-invitation-url: http://localhost:8040/invitation-url  # invitation-url oob-invitation-url
agent-api-url: http://localhost:8021
log-level: debug  # info debug
wallet-type: askar  # askar indy
use-multitenancy: true
enable-webhook: false
delete-data-at-exit: true

enable-invitation-with-proof: false
issuer-invitation-url-with-proof: http://localhost:8040/oob-invitation-url-with-proof