issuer-invitation-url: http://localhost:8040/invitation-url  # invitation-url oob-invitation-url
agent-api-url: http://localhost:8021
log-level: debug     # example: info, debug
wallet-type: askar   # example: askar, indy
use-multitenancy: true
delete-data-at-exit: true

enable-invitation-with-proof: false
issuer-invitation-url-with-proof: http://localhost:8040/oob-invitation-url-with-proof

sse-server-url: http://localhost:8080 # server-sent-event server, in our case usually the datastore URL